const AssignmentType = {
  GET_ALL_ASSIGNMENT: 'GET_ALL_ASSIGNMENT',
  GET_ALL_SUCCESS_ASSIGNMENT: 'GET_ALL_SUCCESS_ASSIGNMENT',
  GET_ALL_FAILURE_ASSIGNMENT: 'GET_ALL_FAILURE_ASSIGNMENT',

  CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
  CREATE_SUCCESS_ASSIGNMENT: 'CREATE_SUCCESS_ASSIGNMENT',
  CREATE_FAILURE_ASSIGNMENT: 'CREATE_FAILURE_ASSIGNMENT',

  EDIT_ASSIGNMENT: 'EDIT_ASSIGNMENT',
  EDIT_SUCCESS_ASSIGNMENT: 'EDIT_SUCCESS_ASSIGNMENT',
  EDIT_FAILURE_ASSIGNMENT: 'EDIT_FAILURE_ASSIGNMENT',

  DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',
  DELETE_SUCCESS_ASSIGNMENT: 'DELETE_SUCCESS_ASSIGNMENT',
  DELETE_FAILURE_ASSIGNMENT: 'DELETE_FAILURE_ASSIGNMENT',
}
export default AssignmentType
