const AssignmentType = {
  GET_ALL_MOCKINGTEST: 'GET_ALL_MOCKINGTEST',
  GET_ALL_SUCCESS_MOCKINGTEST: 'GET_ALL_SUCCESS_MOCKINGTEST',
  GET_ALL_FAILURE_MOCKINGTEST: 'GET_ALL_FAILURE_MOCKINGTEST',

  CREATE_MOCKINGTEST: 'CREATE_MOCKINGTEST',
  CREATE_SUCCESS_MOCKINGTEST: 'CREATE_SUCCESS_MOCKINGTEST',
  CREATE_FAILURE_MOCKINGTEST: 'CREATE_FAILURE_MOCKINGTEST',

  EDIT_MOCKINGTEST: 'EDIT_MOCKINGTEST',
  EDIT_SUCCESS_MOCKINGTEST: 'EDIT_SUCCESS_MOCKINGTEST',
  EDIT_FAILURE_MOCKINGTEST: 'EDIT_FAILURE_MOCKINGTEST',

  DELETE_MOCKINGTEST: 'DELETE_MOCKINGTEST',
  DELETE_SUCCESS_MOCKINGTEST: 'DELETE_SUCCESS_MOCKINGTEST',
  DELETE_FAILURE_MOCKINGTEST: 'DELETE_FAILURE_MOCKINGTEST',
}
export default AssignmentType
