const AssignmentType = {
  GET_ALL_RESPONSE: 'GET_ALL_RESPONSE',
  GET_ALL_SUCCESS_RESPONSE: 'GET_ALL_SUCCESS_RESPONSE',
  GET_ALL_FAILURE_RESPONSE: 'GET_ALL_FAILURE_RESPONSE',

  CREATE_RESPONSE: 'CREATE_RESPONSE',
  CREATE_SUCCESS_RESPONSE: 'CREATE_SUCCESS_RESPONSE',
  CREATE_FAILURE_RESPONSE: 'CREATE_FAILURE_RESPONSE',

  EDIT_RESPONSE: 'EDIT_RESPONSE',
  EDIT_SUCCESS_RESPONSE: 'EDIT_SUCCESS_RESPONSE',
  EDIT_FAILURE_RESPONSE: 'EDIT_FAILURE_RESPONSE',

  DELETE_RESPONSE: 'DELETE_RESPONSE',
  DELETE_SUCCESS_RESPONSE: 'DELETE_SUCCESS_RESPONSE',
  DELETE_FAILURE_RESPONSE: 'DELETE_FAILURE_RESPONSE',
}
export default AssignmentType
