const AssignmentType = {
  GET_ALL_VIDEO: 'GET_ALL_VIDEO',
  GET_ALL_SUCCESS_VIDEO: 'GET_ALL_SUCCESS_VIDEO',
  GET_ALL_FAILURE_VIDEO: 'GET_ALL_FAILURE_VIDEO',
  GET_ALL_VIDEO_DROPDOWN: 'GET_ALL_VIDEO_DROPDOWN',
  GET_ALL_SUCCESS_VIDEO_DROPDOWN: 'GET_ALL_SUCCESS_VIDEO_DROPDOWN',
  SET_VISIBLE:'SET_VISIBLE',

  CREATE_VIDEO: 'CREATE_VIDEO',
  CREATE_SUCCESS_VIDEO: 'CREATE_SUCCESS_VIDEO',
  CREATE_FAILURE_VIDEO: 'CREATE_FAILURE_VIDEO',

  EDIT_VIDEO: 'EDIT_VIDEO',
  EDIT_SUCCESS_VIDEO: 'EDIT_SUCCESS_VIDEO',
  EDIT_FAILURE_VIDEO: 'EDIT_FAILURE_VIDEO',

  DELETE_VIDEO: 'DELETE_VIDEO',
  DELETE_SUCCESS_VIDEO: 'DELETE_SUCCESS_VIDEO',
  DELETE_FAILURE_VIDEO: 'DELETE_FAILURE_VIDEO',
}
export default AssignmentType
